Bugfixes.
jakewtaylor/react-google-font-loader pull request #2
Opened 2018-12-07 20:09 UTC by SalemPCF

I've required 'font' attribute to make sure the user passes a font in all their objects passed.
I've also updated the core logic to support cases where weights aren't supplied. - I noticed this happen when I tried to include the Material Icons font (Material+Icons) because it doesn't take any weights.

2018-12-08 03:22 UTC, jakewtaylor requested changes
See comments inside on code - thanks!

2018-12-08 03:22 UTC, jakewtaylor commented on src/index.js
> +            const weights = font.weights instanceof Array && font.weights.length > 0 ? font.weights.join(',') : '';
This seems a bit over-complicated - we have prop types saying this must be an array, so the `instanceof Array` is redundant (also, I think it would be better to use `Array.isArray` instead if we had to).

Is there any way to allow the `weights` property in the `fonts` shape to be optional?
Something like this?
```JavaScript
propTypes = {
  fonts: PropTypes.arrayOf(PropTypes.shape({
    font: PropTypes.string.isRequired,
    weights: PropTypes.oneOfType([
      PropTypes.arrayOf(PropTypes.int),
      PropTypes.oneOf([null, undefined]),
    ]),
  })).isRequired,
}
```

If so, we can switch this logic to something like this:

```JavaScript
const families = fonts.reduce((acc, font) => {
  const family = font.font.replace(/ +/g, '+');
  const weights = (font.weights || []).join(',')

  acc.push(family + (weights && `:${weights}`));

  return acc;
}, []).join('|');
```

This would be a lot cleaner IMO, but I'm not sure if prop types will work like that.

Do you know if that can be done?

2018-12-08 14:14 UTC, SalemPCF commented on src/index.js
> +            const weights = font.weights instanceof Array && font.weights.length > 0 ? font.weights.join(',') : '';
Ammended PR!

2018-12-10 09:10 UTC, jakewtaylor approved these changes

2018-12-10 09:10 UTC, merged

2018-12-10 09:11 UTC, jakewtaylor commented
Thanks, I'll test and release now!

2018-12-10 09:22 UTC, jakewtaylor commented
Published as `v1.0.3`!

@SalemPCF

2018-12-10 09:23 UTC, SalemPCF commented
Awesome! :)

2018-12-10 09:25 UTC, jakewtaylor commented on src/index.js
> +            const weights = font.weights instanceof Array && font.weights.length > 0 ? font.weights.join(',') : '';
Yep that works great, don't know why I over-complicated the prop types in my head. 😆